@startsalt
{+
    
    {/sweeper|look   }[exit]
    
        {+
        .
        .
        .
        .
        [play               ]
        .
        .
        .
        .
        } |
        {+
        .
        .
        [level]
        [highscore]
        [currscore]
        .
        .
        .
        }
    
    
}
@endsalt